name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run check
      - run: npm run test:unit -- --run
      - run: npm run build
      - name: Generate changelog
        id: changelog
        shell: bash
        run: |
          prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "## What's Changed" > CHANGELOG.md
          if [ -n "$prev_tag" ]; then
            git log "$prev_tag"..HEAD --pretty=format:"- %s" >> CHANGELOG.md
          else
            git log --pretty=format:"- %s" >> CHANGELOG.md
          fi
          echo "body<<'EOF'" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.body }}
          files: build/**
